### ISSUE TITLE
Error when sending an event in Piano Analytics.

### ISSUE THREAD

**Issue by tomwallyn** [alex596/piano_analytics_plugin#1]
I have this error when sending an event in Piano Analytics. 

**E/PIANO-ANALYTICS(17962): Utils.getConnection : java.lang.SecurityException: getDataNetworkTypeForSubscriber**

As a result, I am not receiving any data on my dashboard. I am using Flutter 3.10 and an Android phone. I added the ACCESS_NETWORK_STATE permission in the AndroidManifest.xml, thinking it could be the cause, but it still doesn't work.

**Comment by alex596** [comment]
Salut, pouvez-vous m'en dire plus sur votre erreur ? Utilisez-vous un proxy d'entreprise ?

**Comment by alex596** [comment]
Hi, can you tell me more about your mistake? Are you using a corporate proxy?
