### ISSUE TITLE
PADefaultConfiguration redeclaration

### ISSUE THREAD

**Issue by oscarnarsomnio** [alex596/piano_analytics_plugin#11]
Currently, we have two `PADefaultConfiguration` declations, in two different files.  I think this file (`ios/Classes/PADefaultConfiguration_1.swift`) should be removed from package.

When we add package and run in iOS, without call the plugin, we see the follow log.

<details>
<summary>Log</summary>
<pre>
Launching lib/main/main_production.dart on iPhone SE (3rd generation) in debug mode...
Xcode build done.                                           10.0s
Failed to build iOS app
Swift Compiler Error (Xcode): Invalid redeclaration of 'PADefaultConfiguration'
/Users/damon/.pub-cache/hosted/pub.dev/piano_analytics_plugin-0.0.6/ios/Classes/PADefaultConfiguration.swift:10:7
PADefaultConfiguration.swift:10

Swift Compiler Error (Xcode): Cannot convert value of type 'DarwinBoolean' to expected argument type 'Bool'
/Users/damon/.pub-cache/hosted/pub.dev/piano_analytics_plugin-0.0.6/ios/Classes/PianoAnalyticsPlugin.swift:26:97
PianoAnalyticsPlugin.swift:26

Swift Compiler Error (Xcode): Instance member 'DEFAULT_CRASH_DETECTION' cannot be used on type 'PADefaultConfiguration'
/Users/damon/.pub-cache/hosted/pub.dev/piano_analytics_plugin-0.0.6/ios/Classes/PianoAnalyticsPlugin.swift:26:74
PianoAnalyticsPlugin.swift:26

Swift Compiler Error (Xcode): Instance member 'DEFAULT_SESSION_BACKGROUND_DURATION' cannot be used on type 'PADefaultConfiguration'
/Users/damon/.pub-cache/hosted/pub.dev/piano_analytics_plugin-0.0.6/ios/Classes/PianoAnalyticsPlugin.swift:28:94
PianoAnalyticsPlugin.swift:28

Swift Compiler Error (Xcode): Cannot convert value of type 'DarwinBoolean' to expected argument type 'Bool'
/Users/damon/.pub-cache/hosted/pub.dev/piano_analytics_plugin-0.0.6/ios/Classes/PianoAnalyticsPlugin.swift:30:133
PianoAnalyticsPlugin.swift:30

Swift Compiler Error (Xcode): Instance member 'DEFAULT_IGNORE_LIMITED_ADVERTISING_TRACKING' cannot be used on type 'PADefaultConfiguration'
/Users/damon/.pub-cache/hosted/pub.dev/piano_analytics_plugin-0.0.6/ios/Classes/PianoAnalyticsPlugin.swift:30:110
PianoAnalyticsPlugin.swift:30

Swift Compiler Error (Xcode): Cannot convert value of type 'DarwinBoolean' to expected argument type 'Bool'
/Users/damon/.pub-cache/hosted/pub.dev/piano_analytics_plugin-0.0.6/ios/Classes/PianoAnalyticsPlugin.swift:32:107
PianoAnalyticsPlugin.swift:32

Swift Compiler Error (Xcode): Instance member 'DEFAULT_SEND_WHEN_OPT_OUT' cannot be used on type 'PADefaultConfiguration'
</pre>
</details>

**Comment by mobiledevh** [comment]
Hello, yes it's breaking our builds here too.
Could you remove the duplicate file and publish a new version?

Thanks a lot :)

**Comment by alex596** [comment]
Hi, sorry for this inconvenience, I will delete this file

**Comment by alex596** [comment]
The version 0.0.7 is available

**Comment by alex596** [comment]
The version 0.0.7 is available
