### ISSUE TITLE
iOS deployment target

### ISSUE THREAD

**Issue by Pavel-dnipro** [alex596/piano_analytics_plugin#2]
Hi, just want to clarify why the target is so high(14)? I checked the ios sdk implementation from piano analytics and they have 10, could be its possible to downgrade plugin target?

**Comment by alex596** [comment]
Hi, yes it is possible. I just left iOS 14 for the sake of harmonization with my main project.

I'm going to downgrade the version

**Comment by alex596** [comment]
Version 0.0.4 is available with target for iOS 10
